export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm p-8">
        <h1 className="text-2xl font-bold mb-6">Privacy Policy</h1>
        <div className="space-y-4 text-gray-600 text-sm">
          <p><strong>Effective Date:</strong> June 10, 2026</p>
          
          <p><strong>1. Information We Collect</strong><br />
          When you use HireMe AI, we collect the resume text you paste. <strong>We do not store your resume text.</strong> It is temporarily processed to generate your results and then discarded. We may also collect your email address if you choose to contact us.</p>
          
          <p><strong>2. How We Use Your Information</strong><br />
          We use your resume text solely to generate optimized resume versions, interview questions, and self-introductions. We do not sell, rent, or share your personal data with third parties.</p>
          
          <p><strong>3. Data Retention</strong><br />
          We retain your resume text only for the duration of your session. No historical data is kept. Your generated results are displayed to you in real-time and are not stored on our servers.</p>
          
          <p><strong>4. Third-Party Services</strong><br />
          We use DeepSeek API to process your resume and generate content. These providers may process data according to their own privacy policies. We do not share your data with any other third parties.</p>
          
          <p><strong>5. Data Security</strong><br />
          We implement reasonable security measures to protect your data during transmission. However, no internet transmission is 100% secure.</p>
          
          <p><strong>6. AI-Generated Content</strong><br />
          The content generated by our AI is for reference only. You are responsible for reviewing and using the output appropriately.</p>
          
          <p><strong>7. Your Privacy Rights (GDPR/CCPA)</strong><br />
          Depending on your location, you may have the right to: access, correct, or delete your personal data; withdraw consent at any time; lodge a complaint with a supervisory authority. To exercise these rights, contact us at <a href="mailto:privacy@hireme-ai.com" className="text-blue-600">privacy@hireme-ai.com</a>.</p>
          
          <p><strong>8. Changes to This Policy</strong><br />
          We may update this policy from time to time. Continued use of the service constitutes acceptance of any changes.</p>
          
          <p><strong>9. Contact Us</strong><br />
          If you have questions, please contact us at: <a href="mailto:privacy@hireme-ai.com" className="text-blue-600">privacy@hireme-ai.com</a></p>
        </div>
      </div>
    </main>
  );
}