export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm p-8">
        <h1 className="text-2xl font-bold mb-6">Terms of Service</h1>
        <div className="space-y-4 text-gray-600 text-sm">
          <p><strong>Effective Date:</strong> June 10, 2026</p>
          
          <p><strong>1. Acceptance of Terms</strong><br />
          By using HireMe AI, you agree to these Terms of Service.</p>
          
          <p><strong>2. Eligibility</strong><br />
          You must be at least 16 years old to use this service. By using HireMe AI, you represent and warrant that you meet this age requirement.</p>
          
          <p><strong>3. Use of Service</strong><br />
          You may use HireMe AI to generate resume optimizations, interview questions, and self-introductions based on the resume text you provide. You agree not to use the service for any illegal or unauthorized purpose. Specifically, you agree NOT to: (a) use the service for any illegal purpose; (b) upload malicious content, including but not limited to viruses, malware, or harmful code; (c) reverse engineer, decompile, or attempt to extract the source code of our service.</p>
          
          <p><strong>4. User Content</strong><br />
          You retain ownership of any resume text you provide. By using the service, you grant us permission to process your content solely for the purpose of providing the service. We do not store your resume text after processing.</p>
          
          <p><strong>5. AI Output</strong><br />
          The content generated by our AI is provided "as is" without warranties of any kind. You are solely responsible for reviewing and using the output appropriately.</p>
          
          <p><strong>6. No Guarantee of Results</strong><br />
          HireMe AI provides AI-generated suggestions for interview preparation. We do not guarantee that using our service will result in job interviews, job offers, or any specific career outcome.</p>
          
          <p><strong>7. Limitation of Liability</strong><br />
          HireMe AI is not responsible for any outcomes resulting from your use of the service, including but not limited to job applications or interviews. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages.</p>
          
          <p><strong>8. Termination</strong><br />
          We reserve the right to suspend or terminate access to the service for violation of these terms, without prior notice. You may stop using the service at any time.</p>
          
          <p><strong>9. Changes to Terms</strong><br />
          We may modify these terms at any time. Continued use of the service constitutes acceptance of the modified terms. If you do not agree to the modified terms, you should stop using the service.</p>
          
          <p><strong>10. Contact Us</strong><br />
          Questions? Contact us at: <a href="mailto:legal@hireme-ai.com" className="text-blue-600">legal@hireme-ai.com</a></p>
        </div>
      </div>
    </main>
  );
}