export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-orange-50 py-12 px-4">
      <div className="mx-auto max-w-3xl rounded-2xl border border-orange-100 bg-white p-8 shadow-sm">
        <h1 className="mb-6 text-2xl font-bold text-gray-900">Terms of Service</h1>
        <div className="space-y-4 text-sm text-gray-600">
          <p><strong>Effective Date:</strong> June 22, 2026</p>

          <p><strong>1. Acceptance of Terms</strong><br />
          By using HireMe AI, you agree to these Terms of Service.</p>

          <p><strong>2. Eligibility</strong><br />
          You must be at least 16 years old to use this service. By using HireMe AI, you represent
          and warrant that you meet this age requirement.</p>

          <p><strong>3. Use of Service</strong><br />
          You may use HireMe AI to generate resume optimizations, interview questions, and
          self-introductions based on the resume text you provide. You may optionally specify a
          target company or industry to receive tailored output. You agree not to use the service
          for any illegal or unauthorized purpose.</p>

          <p><strong>4. User Content</strong><br />
          You retain ownership of any resume text you provide. By using the service, you grant us
          permission to process your content solely for the purpose of providing the service. We do
          not store your resume text after processing.</p>

          <p><strong>5. AI Output &amp; ATS Targeting</strong><br />
          All content generated by our AI is labeled as &quot;AI-generated suggestions, for reference
          only.&quot; When you specify a target company or industry, the AI produces tailored
          suggestions based on publicly known hiring patterns — this is not a guarantee of passing
          any ATS system or receiving an interview. You are solely responsible for reviewing and
          using the output appropriately.</p>

          <p><strong>6. No Guarantee of Results</strong><br />
          HireMe AI provides AI-generated suggestions for interview preparation. We do not guarantee
          that using our service will result in job interviews, job offers, ATS approval, or any
          specific career outcome.</p>

          <p><strong>7. Payments &amp; Pricing</strong><br />
          HireMe AI offers a free tier (3 lifetime uses per device) and paid options:
          <br />— $1 for 1 additional generation
          <br />— $20 for 200 credits (15 credits per generation, approximately 13 uses)
          <br />
          All payments are processed by Creem, our Merchant of Record. By making a purchase, you
          also agree to Creem&apos;s terms of service. Prices are listed in USD.</p>

          <p><strong>8. Refund Policy</strong><br />
          HireMe AI provides instant digital content services. All payments, once completed, are
          considered delivered in principle and are non-refundable.
          <br /><br />
          To protect your rights, we offer limited refund protection:
          <br />— If you request a refund within <strong>2 hours</strong> of payment and have{' '}
          <strong>not yet used the service</strong> (i.e., have not clicked &quot;Generate&quot;),
          you may request a full refund.
          <br />— Once you have used the service and received AI-generated content, the service is
          considered complete and refunds will not be accepted.
          <br /><br />
          Exceptions (reviewed case by case):
          <br />1. <strong>Technical failure:</strong> Platform technical issues making the service
          completely unavailable.
          <br />2. <strong>Duplicate charge:</strong> System error causing the same order to be
          charged twice.
          <br />3. <strong>Fraudulent transaction:</strong> Verified unauthorized payment.
          <br /><br />
          All refund requests must be submitted to{' '}
          <a href="mailto:contact@hireme-ai.com" className="text-orange-600 hover:underline">contact@hireme-ai.com</a>.
          We reserve the right to make the final decision on all refund requests.</p>

          <p><strong>9. Limitation of Liability</strong><br />
          HireMe AI is not responsible for any outcomes resulting from your use of the service,
          including but not limited to job applications or interviews. To the maximum extent
          permitted by law, we shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages.</p>

          <p><strong>10. Termination</strong><br />
          We reserve the right to suspend or terminate access to the service for violation of these
          terms, without prior notice. You may stop using the service at any time.</p>

          <p><strong>11. Changes to Terms</strong><br />
          We may modify these terms at any time. Continued use of the service constitutes acceptance
          of the modified terms.</p>

          <p><strong>12. Contact Us</strong><br />
          Questions? Contact us at:{' '}
          <a href="mailto:legal@hireme-ai.com" className="text-orange-600 hover:underline">legal@hireme-ai.com</a></p>

          <div className="mt-6 flex gap-4 text-sm">
            <a href="/" className="text-orange-600 hover:underline">Home</a>
            <a href="/privacy" className="text-orange-600 hover:underline">Privacy Policy</a>
            <a href="/resources" className="text-orange-600 hover:underline">Resources</a>
          </div>
        </div>
      </div>
    </main>
  );
}
